default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password:

development:
  <<: *default
  database: newsletter_app_development

test:
  <<: *default
  database: newsletter_app_test

production:
  <<: *default
  database: newsletter_app_production
